### PR TITLE
OZ's docstrings, with apologies for them.

### PR DESCRIPTION
**Pull request by olzama**

### CODE REVIEW

**Comment by emilymbender** [comment]
This all looks good EXCEPT it re-inserts the commented out message types that I had removed. @olzama do you know how to take those out? Or is it best to just take them out again as a separate change?

**Comment by emilymbender** [comment]
This now looks like my changes + Mike's changes ... and not yours.

**Comment by olzama** [comment]
That's the latest commit, which fixes the absence of yours and Mike's. I believe my changes are there (can be seen in the first commit).

**Comment by emilymbender** [comment]
Taking a leap and approving --- hopefully this ends up coherent :)

**Pull request merged**
