### PR TITLE
COORD - on daughter, MOD <> on mother

### PR DESCRIPTION
**Pull request by ajcassell**
#564

### CODE REVIEW

**Comment by emilymbender** [comment]
This looks like it's taking care of half of #564.

**Comment by ajcassell** [comment]
> This looks like it's taking care of half of #564.

Which part is missing?

**Comment by emilymbender** [comment]
The part about MOD.

**Comment by ajcassell** [comment]
The MOD <> already exists on the mother. If I interpreted our slack thread correctly, isn't the MOD specified there on line 126? If you are referring to the poss-unary-pron phrase, I did not add the MOD because the issue only mentioned COORD - for that rule. I can add it there as well if needed though.

**Comment by emilymbender** [comment]
"poss-unary-phrase has a similar issue, where it should say [ COORD - ] on the daughter and [ MOD < > ] on the mother."

**Comment by ajcassell** [comment]
This is the poss-unary-phrase, right?
Screen Shot 2024-11-01 at 1 41 44 PM

**Comment by emilymbender** [comment]
I assume so -- and it looks like it is there. So let's call it good.

**Pull request merged**
