### PR TITLE
Test autoformatting with autopep8; just one file for now.

### PR DESCRIPTION
**Pull request by olzama**
Here's what it looks like! If we are happy with this, I can do the rest of the files.

### CODE REVIEW

**Review by dantiston — COMMENTED** [review]
Looks good to me!

**Comment by goodmami** [comment]
Ahh... my brain feels less itchy already.

I notice that this will reveal one place where I occasionally diverge from PEP8, which is aligning variable assignments on the `=` sign. I know the arguments against doing so, but when the code is essentially data I find it easier to spot differences when they are aligned. E.g., from `rtest.py`:

```diff
--- original/rtest.py
+++ fixed/rtest.py
@@ -30,18 +30,18 @@
 
 # COMMON FILES AND DIRECTORIES ################################################
 
-SCRIPT_DIR     = pathlib.Path(__file__).parent.resolve()
-RTEST_DIR      = SCRIPT_DIR / 'tests' / 'regression'
-CHOICES_DIR    = RTEST_DIR / 'choices'
-GRAMMARS_DIR   = RTEST_DIR / 'grammars'
-SKELETONS_DIR  = RTEST_DIR / 'skeletons'
+SCRIPT_DIR = pathlib.Path(__file__).parent.resolve()
+RTEST_DIR = SCRIPT_DIR / 'tests' / 'regression'
+CHOICES_DIR = RTEST_DIR / 'choices'
+GRAMMARS_DIR = RTEST_DIR / 'grammars'
+SKELETONS_DIR = RTEST_DIR / 'skeletons'
 RELATIONS_FILE = SKELETONS_DIR / 'Relations'
-CURRENT_DIR    = RTEST_DIR / 'home' / 'current'
-GOLD_DIR       = RTEST_DIR / 'home' / 'gold'
-TXT_SUITE_DIR  = RTEST_DIR / 'txt-suites'
-LOGS_DIR       = RTEST_DIR / 'logs'
-INDEX          = RTEST_DIR / 'regression-test-index'
-DAT_FILENAME   = 'grm.dat'
+CURRENT_DIR = RTEST_DIR / 'home' / 'current'
+GOLD_DIR = RTEST_DIR / 'home' / 'gold'
+TXT_SUITE_DIR = RTEST_DIR / 'txt-suites'
+LOGS_DIR = RTEST_DIR / 'logs'
+INDEX = RTEST_DIR / 'regression-test-index'
+DAT_FILENAME = 'grm.dat'
```

But I'm prepared to give up this indulgence for the greater good.

**Comment by dantiston** [comment]
@goodmami I'm happy to hear you're willing to give it up for the greater good 🙂

**Comment by olzama** [comment]
Yes, I agree that what Mike had there before is better. Oh well...?

So, should I go ahead and format all files using this tool?

**Pull request merged**
