### PR TITLE
warn validation on det preds + suggestion, tests

### PR DESCRIPTION
**Pull request by ajcassell**
#415 Don't autofill det preds, add suggestion, validation and tests

I made this validation a warn since all predicates are technically (as of right now) not validated for form so I wasn't sure whether blocking a user from making a freeform pred was a good idea. 

Screen Shot 2024-10-19 at 3 06 50 PM
Screen Shot 2024-10-19 at 3 06 41 PM

### CODE REVIEW

**Comment by emilymbender** [comment]
Since exist_q_rel and all_q_rel are grammar preds, they should not have the leading underscore.

**Comment by emilymbender** [comment]
And the idea to make this a warning rather than an error makes sense.

**Comment by ajcassell** [comment]
Ok, I have updated to not have the leading underscore.

**Comment by emilymbender** [comment]
I think the regex should allow for both leading underscore & not. But the suggested form for exist_q_rel and all_q_rel shouldn't have one.

**Comment by ajcassell** [comment]
Got it - I take it you merged this / the code is alright because the updated regex using .* will handle _.* and .*?

**Comment by emilymbender** [comment]
Correct.

**Pull request merged**
