### PR TITLE
Remove skipped tests

### PR DESCRIPTION
**Pull request by olzama**
This is to remove the tests which are currently skipped, if we conclude they were meant to be removed (or if we conclude we can no longer recover what their purpose is).

### CODE REVIEW

**Comment by olzama** [comment]
@curtosis Do you remember if you meant to delete or keep this test?

valchg-jpn-rom
Description: None
Indexed: no
Txt-suite: yes
Choices: yes
Skeleton: yes
Gold: yes
Skipped: yes (not indexed)

It looks like we have everything for it but it is not being run. Any recollection?.. Should it be indexed and skipped or should it be deleted?

**Comment by olzama** [comment]
For now:

6 information structure tests are skipped, which is linked to issue https://github.com/delph-in/matrix/issues/494
1 Sahaptin test, which has always been skipped, I don't know why
1 valence change test which seems to have everything but was never indexed; not sure why

The rest I removed because they either lacked most of the files or were my own tests which I remember that I intended to delete and just managed to confuse the bash script.

**Comment by olzama** [comment]
This is ready to be merged in except it also has the https://github.com/delph-in/matrix/pull/498 in it (which is because rtest was not running properly without it; something about the multiprocessing changes; I did not investigate, seemed easier to just merge the latest version of rtest in. But now it is harder to review and merge... Hm. @goodmami what would be your advice? Perhaps best to strip the https://github.com/delph-in/matrix/pull/498 changes as the whole point of this branch was to have the test changes separately...

**Comment by olzama** [comment]
I suppose it is not harder to review and merge so long as https://github.com/delph-in/matrix/pull/498 is merged first. So this one can just wait? And I will branch off of it for my next task.

**Comment by goodmami** [comment]
> 1 Sahaptin test, which has always been skipped, I don't know why

As I recall, it was too large and took forever to test. The problem with this is it's easy to get out of sync with the current Matrix. I just tested it and it seems to pass (which surprised me, frankly). Here are a few tests and their run times on my laptop:

* tiniest: 0.65s
* Sahaptin-short: 3.26s
* Sahaptin: 15.50s

Regarding this PR and #498, it's fine if you want to merge that first. I'm not sure why exactly it didn't pass without the other commits. Since you've already merged in the changes from #498 into this PR, please rebase before merging this one, otherwise those commits might appear in the history twice. Something like this:

```console
$ git checkout remove-skipped-tests  # if not checked out already
$ git rebase trunk  # after #498 is merged into trunk
```

If there's any issues you maybe be able to `git rebase --abort` to cancel if you want to inspect things first. Sometimes there's a cleaner way to get a clean rebase than a merge commit.

**Comment by goodmami** [comment]
Before merging this I think we should have Emily look over the list of tests. However, this list is not easy to see from the diff of changed files. @olzama, could you write in a comment the list of names of tests removed and maybe a brief reason for their removal? The 'skipped' list (see my [comment](https://github.com/delph-in/matrix/pull/498#issuecomment-671190015) in #498) may be a subset of those?

**Comment by curtosis** [comment]
> @curtosis Do you remember if you meant to delete or keep this test?
> 
> valchg-jpn-rom

> It looks like we have everything for it but it is not being run. Any recollection?.. Should it be indexed and skipped or should it be deleted?

To the best of my recollection, it should be indexed and run. Which is not to say my recollection is 100% accurate, of course.

**Comment by olzama** [comment]
> To the best of my recollection, it should be indexed and run. Which is not to say my recollection is 100% accurate, of course.

It fails currently, I think (if run). I will index it and disable for now (and file an issue).

**Comment by olzama** [comment]
Here's the tests I removed:

adnom-poss-mod-dep-aff-head-non-aff-hf
adnom-poss-mod-dep-non-aff-head-non-aff-hf
adnom-poss-spec-head-aff-hf-block-pron
adnom-poss-spec-possessor-affix-two-strat-mod-spec-var
adnom-poss-spec-possessor-affix-two-strat-order-var
adnom-poss-spec-possessor-non-affix-possessum-non-affix-bidirec
ccomp-extra-and-same
ccomp-oblig-bef-aft-ovs
ccomp-oblig-svo-form
ccomp-v2-vfinal-aux
clausalcomps-v2-vfinal-aux
clausalmods-mod-position
neg-head-comp
neg1b-neg2fd
v2-orig
vfinal

Here's the information about them. As you can see, most of them are missing most of their content. Some aren't but they were unindexed. I am not sure it is worth trying to follow up on each one. As for my own tests, I can testify that I'd been adding and removing lots of tests initially, the reason for removing being that I'd reanalyze what I actually want from the MRS, and then ultimately add a similar test but under a different name, as is evident from, say, ccomp-v2-vfinal-aux and clausalcomps-v2-vfinal-aux; I've been trying to add a test for this functionality but not succeeding for one reason or another; does not matter now. 

It is likely that other people's tests which ended up unindexed are similar. People have decided they did not want them but failed to clean them out fully. It seems cleanest to me to not re-add them but rather to assume that they were  unindexed not by accident but because the author wanted to remove them.

adnom-poss-mod-dep-aff-head-non-aff-hf
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

adnom-poss-mod-dep-non-aff-head-non-aff-hf
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

adnom-poss-spec-head-aff-hf-block-pron
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

adnom-poss-spec-possessor-affix-two-strat-mod-spec-var
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    yes
    Gold:        no
    Skipped:     yes (not indexed)

adnom-poss-spec-possessor-affix-two-strat-order-var
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    yes
    Gold:        no
    Skipped:     yes (not indexed)

adnom-poss-spec-possessor-non-affix-possessum-non-affix-bidirec
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    yes
    Gold:        no
    Skipped:     yes (not indexed)

ccomp-extra-and-same
    Description: None
    Indexed:     no
    Txt-suite:   yes
    Choices:     yes
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

ccomp-oblig-bef-aft-ovs
    Description: None
    Indexed:     no
    Txt-suite:   yes
    Choices:     yes
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

ccomp-oblig-svo-form
    Description: None
    Indexed:     no
    Txt-suite:   yes
    Choices:     yes
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

ccomp-v2-vfinal-aux
    Description: None
    Indexed:     no
    Txt-suite:   yes
    Choices:     yes
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

clausalcomps-v2-vfinal-aux
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

clausalmods-mod-position
    Description: None
    Indexed:     no
    Txt-suite:   yes
    Choices:     yes
    Skeleton:    yes
    Gold:        no
    Skipped:     yes (not indexed)

neg-head-comp
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    yes
    Gold:        no
    Skipped:     yes (not indexed)

neg1b-neg2fd
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     yes
    Skeleton:    no
    Gold:        no
    Skipped:     yes (not indexed)

v2-orig
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

vfinal
    Description: None
    Indexed:     no
    Txt-suite:   no
    Choices:     no
    Skeleton:    no
    Gold:        yes
    Skipped:     yes (not indexed)

**Comment by emilymbender** [comment]
Thanks, Olga. It is helpful to have that catalogue, and it looks reasonable to me to remove all of these.

**Comment by olzama** [comment]
I forgot that there was a separate PR for these tests. I think there has been enough discussion about them, so I am going to just merge this in, I think.

**Pull request merged**
